[project]
name = "ai-act-rag-navigator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.13.2",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.2.0",
    "pymupdf>=1.27.1",
    "python-dotenv>=1.2.1",
    "spacy>=3.8.11",
]
